package com.blueduck.easydentist.ui.auth

import android.app.ProgressDialog
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import com.blueduck.easydentist.databinding.FragmentResetPasswordBinding
import com.blueduck.easydentist.dialog.SimpleMessageDialog
import com.blueduck.easydentist.util.getSimpleProgressDialog
import com.blueduck.easydentist.util.logError
import com.blueduck.easydentist.util.showToast
import com.google.firebase.auth.FirebaseAuth
import dagger.hilt.android.AndroidEntryPoint
import javax.inject.Inject


// ResetPasswordFragment that allows a user to reset their password
@AndroidEntryPoint
class ResetPasswordFragment : Fragment() {
    lateinit var binding: FragmentResetPasswordBinding

    @Inject
    lateinit var firebaseAuth: FirebaseAuth

    private lateinit var progressDialog: ProgressDialog

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {
        // binding variable of type FragmentResetPasswordBinding, which is a class generated by the data binding library that holds references to the views in the layout file associated with this fragment.
        binding = FragmentResetPasswordBinding.inflate(inflater, container, false)
        configureUi()
        return binding.root
    }

    private fun configureUi() {
        progressDialog = getSimpleProgressDialog(requireContext())
        setClickListeners()
    }

    private fun setClickListeners() {
        binding.ivBackBtn.setOnClickListener { requireActivity().onBackPressed() }
        binding.btnSendMail.setOnClickListener {
            if (binding.etEmail.text.isNullOrEmpty()) {
                showToast("Please enter the email associated with your account.")
            } else {
                sendEmailToResetPassword()
            }
        }
    }

    // this function calls sendPasswordResetEmail() on the firebaseAuth instance to send the password reset email to the user.
    private fun sendEmailToResetPassword() {
        val email = binding.etEmail.text.toString()
        progressDialog.show()
        firebaseAuth.sendPasswordResetEmail(email)
                // The addOnCompleteListener() callback is called when the password reset email is sent successfully, and shows a message dialog with a message to check the email inbox and reset the password.
            .addOnCompleteListener { task ->
                if (task.isSuccessful) {
                    SimpleMessageDialog(
                        requireActivity(),
                        "we have sent an email to your associated account email address to help you reset your password. Please check your inbox and follow the instructions provided in the email to reset your password.",
                        onOkClick = {}
                    ).show()
                } else {
                    logError("Error Occurred")
                }
                progressDialog.dismiss()
            }.addOnFailureListener {
                showToast(it.message.toString())
                progressDialog.dismiss()
            }
    }

}